[build]
  publish = "."
  command = "echo 'No build command'"

[functions]
  directory = "netlify/functions"
  node_bundle = true
  timeout = 60

[[redirects]]
  from = "/api/data"
  to = "/.netlify/functions/scraper"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200